// const GOTV = [
//   {
//     id: 17,
//     cableplan_id: "17",
//     cable: "GOTV",
//     package: "GOtv Smallie-monthly 800",
//     plan_amount: "796",
//   },
//   {
//     id: 16,
//     cableplan_id: "16",
//     cable: "GOTV",
//     package: "GOtv Jinja",
//     plan_amount: "1640",
//   },
//   {
//     id: 35,
//     cableplan_id: "35",
//     cable: "GOTV",
//     package: "GOtv Smallie - Quarterly",
//     plan_amount: "2100",
//   },
//   {
//     id: 47,
//     cableplan_id: "47",
//     cable: "GOTV",
//     package: "Gotv-jolli",
//     plan_amount: "2460",
//   },
//   {
//     id: 2,
//     cableplan_id: "2",
//     cable: "GOTV",
//     package: "GOtv Max",
//     plan_amount: "3600",
//   },
//   {
//     id: 36,
//     cableplan_id: "36",
//     cable: "GOTV",
//     package: "GOtv Smallie - Yearly",
//     plan_amount: "6200",
//   },
// ];
// const DSTV = [
//   {
//     id: 33,
//     cableplan_id: "33",
//     cable: "DSTV",
//     package: "DStv Padi 1850.",
//     plan_amount: "1841",
//   },
//   {
//     id: 6,
//     cableplan_id: "6",
//     cable: "DSTV",
//     package: "DStv Yanga",
//     plan_amount: "2565",
//   },
//   {
//     id: 22,
//     cableplan_id: "22",
//     cable: "DSTV",
//     package: "DSTV CONFAM",
//     plan_amount: "4587",
//   },
//   {
//     id: 23,
//     cableplan_id: "23",
//     cable: "DSTV",
//     package: "DStv Asia",
//     plan_amount: "6200",
//   },
//   {
//     id: 7,
//     cableplan_id: "7",
//     cable: "DSTV",
//     package: "DStv Compact",
//     plan_amount: "7900",
//   },
//   {
//     id: 29,
//     cableplan_id: "29",
//     cable: "DSTV",
//     package: "DStv Compact + Extra View",
//     plan_amount: "10400",
//   },
//   {
//     id: 8,
//     cableplan_id: "8",
//     cable: "DSTV",
//     package: "DStv Compact Plus",
//     plan_amount: "12400",
//   },
//   {
//     id: 32,
//     cableplan_id: "32",
//     cable: "DSTV",
//     package: "DStv compact plus + extra view",
//     plan_amount: "14826",
//   },
//   {
//     id: 9,
//     cableplan_id: "9",
//     cable: "DSTV",
//     package: "DStv Premium",
//     plan_amount: "17940",
//   },
//   {
//     id: 34,
//     cableplan_id: "34",
//     cable: "DSTV",
//     package: "DStv premium extra view",
//     plan_amount: "20796",
//   },
// ];
// const STARTIME = [
//   {
//     id: 42,
//     cableplan_id: "42",
//     cable: "STARTIME",
//     package: "Nova - 90 Naira - 1 Day",
//     plan_amount: "90",
//   },
//   {
//     id: 43,
//     cableplan_id: "43",
//     cable: "STARTIME",
//     package: "Basic - 160 Naira - 1 Day",
//     plan_amount: "160",
//   },
//   {
//     id: 44,
//     cableplan_id: "44",
//     cable: "STARTIME",
//     package: "Smart - 200 Naira - 1 Day",
//     plan_amount: "200",
//   },
//   {
//     id: 37,
//     cableplan_id: "37",
//     cable: "STARTIME",
//     package: "Nova - 300 Naira - 1 Week",
//     plan_amount: "300",
//   },
//   {
//     id: 45,
//     cableplan_id: "45",
//     cable: "STARTIME",
//     package: "Classic - 320 Naira - 1 Day",
//     plan_amount: "320",
//   },
//   {
//     id: 46,
//     cableplan_id: "46",
//     cable: "STARTIME",
//     package: "Super - 400 Naira - 1 Day",
//     plan_amount: "400",
//   },
//   {
//     id: 38,
//     cableplan_id: "38",
//     cable: "STARTIME",
//     package: "Basic - 600 Naira - 1 Week",
//     plan_amount: "600",
//   },
//   {
//     id: 39,
//     cableplan_id: "39",
//     cable: "STARTIME",
//     package: "Smart - 700 Naira - 1 Week",
//     plan_amount: "700",
//   },
//   {
//     id: 24,
//     cableplan_id: "24",
//     cable: "STARTIME",
//     package: "NOVA-900-1 month",
//     plan_amount: "900",
//   },
//   {
//     id: 40,
//     cableplan_id: "40",
//     cable: "STARTIME",
//     package: "Classic - 1200 Naira - 1 Week",
//     plan_amount: "1200",
//   },
//   {
//     id: 41,
//     cableplan_id: "41",
//     cable: "STARTIME",
//     package: "Super - 1,500 Naira - 1 Week",
//     plan_amount: "1500",
//   },
//   {
//     id: 49,
//     cableplan_id: "49",
//     cable: "STARTIME",
//     package: "Basic-1,700 Naira- 1 Month",
//     plan_amount: "1700",
//   },
//   {
//     id: 25,
//     cableplan_id: "25",
//     cable: "STARTIME",
//     package: "BASIC-1700-1month",
//     plan_amount: "1700",
//   },
//   {
//     id: 26,
//     cableplan_id: "26",
//     cable: "STARTIME",
//     package: "Smart-2200-1month",
//     plan_amount: "2200",
//   },
//   {
//     id: 51,
//     cableplan_id: "51",
//     cable: "STARTIME",
//     package: "Smart - 2,200 Naira - 1Month",
//     plan_amount: "2200",
//   },
//   {
//     id: 27,
//     cableplan_id: "27",
//     cable: "STARTIME",
//     package: "Classic-2500-1month",
//     plan_amount: "2500",
//   },
//   {
//     id: 50,
//     cableplan_id: "50",
//     cable: "STARTIME",
//     package: "classic -2,500 Naira- 1Month",
//     plan_amount: "2500",
//   },
//   {
//     id: 28,
//     cableplan_id: "28",
//     cable: "STARTIME",
//     package: "Super-4200-1month",
//     plan_amount: "4200",
//   },
//   {
//     id: 48,
//     cableplan_id: "48",
//     cable: "STARTIME",
//     package: "Super-4,200 Naira- 1 Month",
//     plan_amount: "4200",
//   },
// ];
const GOTV = [
  {
    planName: "GOtv Smallie - monthly",
    planId: "GOTV_SMALLIE_MONTHLY",
    cableName: "GOTV",
    price: 1675,
    resellerPrice: 1625,
    apiPrice: 1595,
  },
  {
    planName: "GOtv Jinja Bouquet",
    planId: "GOTV_JINJA",
    cableName: "GOTV",
    price: 3400,
    resellerPrice: 3350,
    apiPrice: 3320,
  },
  {
    planName: "GOtv Smallie - quarterly",
    planId: "GOTV_SMALLIE_QUARTERLY",
    cableName: "GOTV",
    price: 4275,
    resellerPrice: 4225,
    apiPrice: 4195,
  },
  {
    planName: "GOtv Jolli Bouquet",
    planId: "GOTV_JOLLI",
    cableName: "GOTV",
    price: 4950,
    resellerPrice: 4900,
    apiPrice: 4870,
  },
  {
    planName: "GOtv Max Bouquet",
    planId: "GOTV_MAX",
    cableName: "GOTV",
    price: 7300,
    resellerPrice: 7250,
    apiPrice: 7220,
  },
  {
    planName: "GOtv Open_",
    planId: "GOTV_OPEN",
    cableName: "GOTV",
    price: 6700,
    resellerPrice: 6650,
    apiPrice: 6620,
  },
  {
    planName: "GOtv Supa Bouquet",
    planId: "GOTV_SUPA",
    cableName: "GOTV",
    price: 9700,
    resellerPrice: 9650,
    apiPrice: 9620,
  },
  {
    planName: "GOtv Smallie - yearly",
    planId: "GOTV_SMALLIE_YEARLY",
    cableName: "GOTV",
    price: 12400,
    resellerPrice: 12350,
    apiPrice: 12320,
  },
  {
    planName: "GOtv Supa Plus",
    planId: "GOTV_SUPA_PLUS",
    cableName: "GOTV",
    price: 15800,
    resellerPrice: 15750,
    apiPrice: 15720,
  },
  {
    planName: "GOtv Supa Plus - Annual_",
    planId: "GOTV_SUPA_PLUS_ANNUAL",
    cableName: "GOTV",
    price: 126100,
    resellerPrice: 126050,
    apiPrice: 126020,
  },
];
const DSTV = [
  {
    planName: "DStv Fta Plus",
    planId: "DSTV_FTA",
    cableName: "DSTV",
    price: 1700,
    resellerPrice: 1650,
    apiPrice: 1620,
  },
  {
    planName: "DStv Padi",
    planId: "DSTV_PADI",
    cableName: "DSTV",
    price: 3700,
    resellerPrice: 3650,
    apiPrice: 3620,
  },
  {
    planName: "DStv HDPVR Access Service",
    planId: "DSTV_HDPVR_ACCESS_SERVICE",
    cableName: "DSTV",
    price: 5100,
    resellerPrice: 5050,
    apiPrice: 5020,
  },
  {
    planName: "DStv French Touch",
    planId: "DSTV_FRENCH_TOUCH",
    cableName: "DSTV",
    price: 5900,
    resellerPrice: 5850,
    apiPrice: 5820,
  },
  {
    planName: "DStv Yanga Bouquet E36",
    planId: "DSTV_YANGA",
    cableName: "DSTV",
    price: 5200,
    resellerPrice: 5150,
    apiPrice: 5120,
  },
  {
    planName: "DStv Yanga OTT Streaming Subscription",
    planId: "DSTV_YANGA_STREAMING",
    cableName: "DSTV",
    price: 5200,
    resellerPrice: 5150,
    apiPrice: 5120,
  },
  {
    planName: "DStv GWALLE36 - Great Wall Standalone Bouquet E36 + Showmax",
    planId: "DSTV_GWALL_SHOWMAX",
    cableName: "DSTV",
    price: 6725,
    resellerPrice: 6675,
    apiPrice: 6645,
  },
  {
    planName: "DStv Yanga Bouquet E36 + Showmax",
    planId: "DSTV_YANGA_SHOWMAX",
    cableName: "DSTV",
    price: 6650,
    resellerPrice: 6600,
    apiPrice: 6570,
  },
  {
    planName: "DStv Padi Bouquet E36 + Showmax",
    planId: "DSTV_PADI_SHOWMAX",
    cableName: "DSTV",
    price: 6200,
    resellerPrice: 6150,
    apiPrice: 6120,
  },
  {
    planName: "DStv Confam Bouquet E36",
    planId: "DSTV_CONFAM",
    cableName: "DSTV",
    price: 9400,
    resellerPrice: 9350,
    apiPrice: 9320,
  },
  {
    planName: "DStv Comfam Streaming Subscription",
    planId: "DSTV_CONFAM_STREAMING",
    cableName: "DSTV",
    price: 9400,
    resellerPrice: 9350,
    apiPrice: 9320,
  },
  {
    planName: "DStv Comfam Bouquet E36 + Showmax",
    planId: "DSTV_CONFAM_SHOWMAX",
    cableName: "DSTV",
    price: 10850,
    resellerPrice: 10800,
    apiPrice: 10770,
  },
  {
    planName: "DStv Indian_",
    planId: "DSTV_ASIAN",
    cableName: "DSTV",
    price: 12500,
    resellerPrice: 12450,
    apiPrice: 12420,
  },
  {
    planName: "DStv Compact",
    planId: "DSTV_COMPACT",
    cableName: "DSTV",
    price: 15800,
    resellerPrice: 15750,
    apiPrice: 15720,
  },
  {
    planName: "DStv Compact Streaming Subscription",
    planId: "DSTV_COMPACT_STREAMING",
    cableName: "DSTV",
    price: 15800,
    resellerPrice: 15750,
    apiPrice: 15720,
  },
  {
    planName: "DStv Premium East Africa and Indian_",
    planId: "DSTV_PREMIUM_EAST_AFRICA_",
    cableName: "DSTV",
    price: 16630,
    resellerPrice: 16580,
    apiPrice: 16550,
  },
  {
    planName: "DStv Compact Bouquet E36 + Showmax",
    planId: "DSTV_COMPACT_SHOWMAX",
    cableName: "DSTV",
    price: 17250,
    resellerPrice: 17200,
    apiPrice: 17170,
  },
  {
    planName: "DStv French Plus_",
    planId: "DSTV_FRENCH_PLUS",
    cableName: "DSTV",
    price: 20600,
    resellerPrice: 20550,
    apiPrice: 20520,
  },
  {
    planName: "DStv Compact Plus",
    planId: "DSTV_COMPACT_PLUS",
    cableName: "DSTV",
    price: 25100,
    resellerPrice: 25050,
    apiPrice: 25020,
  },
  {
    planName: "DStv Compact Plus Streaming Subscription",
    planId: "DSTV_COMPACT_PLUS_STREAMING",
    cableName: "DSTV",
    price: 25100,
    resellerPrice: 25050,
    apiPrice: 25020,
  },
  {
    planName: "DStv Compact Plus Bouquet E36 + Showmax",
    planId: "DSTV_COMPACT_PLUS_SHOWMAX",
    cableName: "DSTV",
    price: 26550,
    resellerPrice: 26500,
    apiPrice: 26470,
  },
  {
    planName: "DStv Premium W/Afr E36 + ASIAE36 + Showmax",
    planId: "DSTV_PREMIUM_ASIA_SHOWMAX",
    cableName: "DSTV",
    price: 27600,
    resellerPrice: 27550,
    apiPrice: 27520,
  },
  {
    planName: "DStv Premium",
    planId: "DSTV_PREMIUM",
    cableName: "DSTV",
    price: 37100,
    resellerPrice: 37050,
    apiPrice: 37020,
  },
  {
    planName: "DStv Premium Streaming Subscription",
    planId: "DSTV_PREMIUM_STREAMING",
    cableName: "DSTV",
    price: 37100,
    resellerPrice: 37050,
    apiPrice: 37020,
  },
  {
    planName: "DStv Premium W/Afr E36 + Showmax",
    planId: "DSTV_PREMIUM_SHOWMAX",
    cableName: "DSTV",
    price: 37100,
    resellerPrice: 37050,
    apiPrice: 37020,
  },
  {
    planName: "DStv Premium W/Afr + Asian Bouquet E36_",
    planId: "DSTV_PREMIUM_ASIA",
    cableName: "DSTV",
    price: 42100,
    resellerPrice: 42050,
    apiPrice: 42020,
  },
  {
    planName: "DStv Asian Bouquet E36 + Showmax",
    planId: "DSTV_ASIA_SHOWMAX",
    cableName: "DSTV",
    price: 15000,
    resellerPrice: 14950,
    apiPrice: 14920,
  },
  {
    planName: "DStv Premium French",
    planId: "DSTV_PREMIUM_FRENCH",
    cableName: "DSTV",
    price: 57600,
    resellerPrice: 57550,
    apiPrice: 57520,
  },
  {
    planName: "DStv Premium W/Afr + French Bonus Bouquet E36 + Showmax",
    planId: "DSTV_PREMIUM_FRENCH_WAF_SHOWMAX",
    cableName: "DSTV",
    price: 57600,
    resellerPrice: 57550,
    apiPrice: 57520,
  },
  {
    planName: "DStv Prestige",
    planId: "DSTV_PRESTIGE",
    cableName: "DSTV",
    price: 850100,
    resellerPrice: 850050,
    apiPrice: 850020,
  },
];
const SHOWMAX = [
  {
    planName: "Entertainment (Mobile) for 1 month",
    planId: "SHOWMAX_ENTERTAINMENT_MOBILE_ONLY_1",
    cableName: "SHOWMAX",
    price: 1700,
    resellerPrice: 1650,
    apiPrice: 1620,
  },
  {
    planName: "Entertainment (All Devices) for 1 month",
    planId: "SHOWMAX_ENTERTAINMENT_ALL_DEVICES_1",
    cableName: "SHOWMAX",
    price: 3600,
    resellerPrice: 3550,
    apiPrice: 3520,
  },
  {
    planName: "Entertainment (Mobile) for 3 month",
    planId: "SHOWMAX_ENTERTAINMENT_MOBILE_ONLY_3",
    cableName: "SHOWMAX",
    price: 3900,
    resellerPrice: 3850,
    apiPrice: 3820,
  },
  {
    planName: "Premier League (Mobile) for 1 month",
    planId: "SHOWMAX_PL_MOBILE_1",
    cableName: "SHOWMAX",
    price: 3300,
    resellerPrice: 3250,
    apiPrice: 3220,
  },
  {
    planName: "Entertainment (Mobile) + PL (Mobile) for 1 month",
    planId: "SHOWMAX_ENTERTAINMENT_MOBILE_PL_MOBILE_1",
    cableName: "SHOWMAX",
    price: 4100,
    resellerPrice: 4050,
    apiPrice: 4020,
  },
  {
    planName: "Entertainment (All Devices) + PL (Mobile) Bundle for 1 month",
    planId: "SHOWMAX_ENTERTAINMENT_ALL_DEVICES_PL_MOBILE_1",
    cableName: "SHOWMAX",
    price: 5500,
    resellerPrice: 5450,
    apiPrice: 5420,
  },
  {
    planName: "Entertainment (Mobile) for 6 month",
    planId: "SHOWMAX_ENTERTAINMENT_MOBILE_ONLY_6",
    cableName: "SHOWMAX",
    price: 6800,
    resellerPrice: 6750,
    apiPrice: 6720,
  },
  {
    planName: "Entertainment (All Devices) for 3 month",
    planId: "SHOWMAX_ENTERTAINMENT_ALL_DEVICES_3",
    cableName: "SHOWMAX",
    price: 8500,
    resellerPrice: 8450,
    apiPrice: 8420,
  },
  {
    planName: "Premier League (Mobile) for 3 month",
    planId: "SHOWMAX_PL_MOBILE_3",
    cableName: "SHOWMAX",
    price: 9700,
    resellerPrice: 9650,
    apiPrice: 9620,
  },
  {
    planName: "Entertainment (Mobile) + PL (Mobile) for 3 month",
    planId: "SHOWMAX_ENTERTAINMENT_MOBILE_PL_MOBILE_3",
    cableName: "SHOWMAX",
    price: 12100,
    resellerPrice: 12050,
    apiPrice: 12020,
  },
  {
    planName: "Entertainment (All Devices) for 6 month",
    planId: "SHOWMAX_ENTERTAINMENT_ALL_DEVICES_6",
    cableName: "SHOWMAX",
    price: 14800,
    resellerPrice: 14750,
    apiPrice: 14720,
  },
  {
    planName: "Entertainment (All Devices) + PL (Mobile) Bundle for 3 month",
    planId: "SHOWMAX_ENTERTAINMENT_ALL_DEVICES_PL_MOBILE_3",
    cableName: "SHOWMAX",
    price: 16300,
    resellerPrice: 16250,
    apiPrice: 16220,
  },
  {
    planName: "Premier League (Mobile) for 6 month",
    planId: "SHOWMAX_PL_MOBILE_6",
    cableName: "SHOWMAX",
    price: 18300,
    resellerPrice: 18250,
    apiPrice: 18220,
  },
  {
    planName: "Entertainment (Mobile) + PL (Mobile) for 6 month",
    planId: "SHOWMAX_ENTERTAINMENT_MOBILE_PL_MOBILE_6",
    cableName: "SHOWMAX",
    price: 24100,
    resellerPrice: 24050,
    apiPrice: 24020,
  },
  {
    planName: "Entertainment (All Devices) + PL (Mobile) Bundle for 6 month",
    planId: "SHOWMAX_ENTERTAINMENT_ALL_DEVICES_PL_MOBILE_6",
    cableName: "SHOWMAX",
    price: 32500,
    resellerPrice: 32450,
    apiPrice: 32420,
  },
];
const STARTIME = [];
module.exports = { GOTV, DSTV, STARTIME, SHOWMAX };
